export const scaleFactor = 4;

export const dialogueData = {
  pc: `This is Command Central—where I teach online classes, Photoshop my professors into wild NPCs, and work on my latest game: <a href="https://umt.app.box.com/s/q6ugjuccpfufuo331ampy1lsyzbmq2vp" target="_blank">ChallengED</a>. It's a chaotic survival game where you play as a substitute teacher managing a classroom full of unique students, staff chaos, and your own mental stability. Basically… it’s autobiographical.`,
  "degrees": `Here we have a Culinary Arts degree, because I once thought I’d be the next Gordon Ramsay. Then there’s a Bachelor of Science in Health and Human Performance, and a Bachelor of Arts. And now, I’m working on my MA in Interactive Media and Game Design. The only issue is… I don’t want to leave. I love it here! Someone help me. No seriously, send snacks and moral support.`,
  "sofa-table": `This is my sofa. It’s my creative lair, my Netflix binge zone, and also my YouTube channel <a href="https://www.youtube.com/@shanellocke4119" target="_blank">Shanel Locke Art</a>. I also watch trashy reality TV here, because balance, y’know?`,
  "artwork": 'Behold! My multifaceted  <a href="https://www.shanellockeart.com/portfolio" target="_blank">artwork</a>. I make game art and traditional art —I’ve probably even drawn on a tortilla at some point. Creativity doesn’t sleep, it just forgets to hydrate',
  "nightstand1": 'This is my nightstand. It’s organized, calm, and symmetrical. Unlike the rest of my life. I find peace in order… and color-coordinated notebooks.',
  "nightstand2": 'My husband’s nightstand, on the other hand, looks like a miniature Barnes & Noble exploded. He has so many books stacked up, I’m worried he’ll be crushed in the night by the avalanche of knowledge.',
  tv: `That's my TV. When I’m not making games or grading papers, I’m usually watching YouTube.  I've been watching youtubers a lot recently like :
   <a href="https://www.youtube.com/@D3kryption" target="_blank">D3kryption</a>, <a href="https://www.youtube.com/@CasanisPlays" target="_blank">CasanisPlays</a>,
  <a href="https://www.youtube.com/@polymaniac" target="_blank">Poly Maniac</a> (sometimes) and <a href="https://www.youtube.com/@GorkaGames" target="_blank">Gorka Games</a> channels because sometimes the best way to learn is to watch someone else try cool things before I fail spectacularly.`,
  bed: `This bed is more of a suggestion than a destination. I stay up way too late tinkering with game mechanics and experimenting with new tools. But when I do sleep? I sleep like I just rage-quit a boss fight.`,
  resume: `Ah yes, my trusty resume. Always ready, always hopeful. I leave it out in case the job of my dreams magically apparates out of the wall like I’m in a fantasy RPG. Spoiler: hasn’t happened. Yet. <a href="https://www.shanellockeart.com/_files/ugd/27f365_44ddcaa0cc2541fa863473994f77f86c.pdf" target="_blank">Check it out?</a>
  Contact me at shanellockeart@gmail.com if you have any interesting job opportunities!`,
  projects: `Click here to check out my games portfolio! I’ve made games in Unreal, Unity, HTML5—you name it. I once made a game using a toaster and sheer willpower. Okay, not really. But now I want to try <a href="https://www.shanellockeart.com/portfolio-collections/my-portfolio/game-design-and-prototypes" target="_blank">here</a>.`,
  library: `Welcome to my mini-library. I’m big on serious games—games that teach, inform, and sometimes make you cry existentially. Some solid reads? Games, Design, and Play, Serious Games, Games That Educate, Train, and Inform, and Video Game Level Design. If you love games that do more, you’ll love these.`,
  exit: `Ah yes, the sweet serenity of Dutton, Montana—where the cows outnumber the people and the Wi-Fi depends on the wind. I teach college courses online from here, so if you hear a rooster in the background, just roll with it. Anyway, if you want to leave Shanel Locke's portfolio, just… close the tab. I won’t be offended. Probably.`,
  "lamp": 'I love lamp. (Long Pause) …No really, I do. It’s warm, it’s glowy, and it makes me feel like I’m accomplishing things—even when I’m just doom-scrolling.'
};